[[ $TERM != "screen" ]] && exec tmux

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# clear xkbmap options
setxkbmap -option
# set xkbmap options:
# - ctrl:swapcaps   - swap Ctrl and CapsLock
# - grp:lwin_toggle - switch layout using left "win" button
# - lv3:rwin_switch - right "win" switch: no idea what it actually does, but it fixes mapping when using Chrome. https://askubuntu.com/a/1011482
setxkbmap -layout us,ua -option 'ctrl:swapcaps,grp:lwin_toggle,lv3:rwin_switch'

# disable Ctrl-d
set -o ignoreeof

export TERM="xterm-256color"
stty -ixon

# aliases
alias setclip='xclip -selection c'
alias getclip='xclip -selection clipboard -o'
alias save='git add . && git commit -nm save && git push origin `git rev-parse --abbrev-ref HEAD`'

# helpers

[[ -s "/home/joseph/.gvm/scripts/gvm" ]] && source "/home/joseph/.gvm/scripts/gvm"

vget() {
  [ $# -eq 0 ] && echo 'Usage:\n\t vget <git_repo_clone_url> [git_ref]'
  a=$1
  p=vendor/${a:8}
  if [ ! -d $p ] || [ ! -d "$p/.git" ]; then
    echo 'Clone...'
    rm -rf $p > /dev/null 2>&1
    git clone $a $p > /dev/null 2>&1
  fi
  _pwd=`pwd`
  if [ $# -eq 2 ]; then
    echo "Check out $2"
    cd $p && git checkout $2 > /dev/null 2>&1
    if [ $? -ne 0 ]; then
      echo "git checkout FAILED. Rerun vget with correct git ref or go to $p, checkout manually and delete .git"
      cd $_pwd
      return 1
    fi
  fi
  cd $_pwd
  echo 'Remove .git'
  rm -rf "$p/.git"
  echo 'Done.'
}

source $HOME/.config/zaw/zaw.zsh
alias gop="hsandbox go"

eval "$(direnv hook zsh)"

batlife() {
    upower -i /org/freedesktop/UPower/devices/battery_BAT0
}

set_wacom_output() {
    $o=eDP1
    if [ $# -eq 1 ]; then
        $o=$1
    fi
    xsetwacom --set "Wacom Bamboo Connect Pen stylus" MapToOutput $o
}

vimg() {
    vim -c 'tab sball' `git status --porcelain | sed -ne 's/^ M //p'`
}


d_mysql() {
    mysql -h 127.0.0.1 -u root
}


# added by travis gem
[ -f /home/joseph/.travis/travis.sh ] && source /home/joseph/.travis/travis.sh

command -v vg >/dev/null 2>&1 && eval "$(vg eval --shell zsh)"

eval `dircolors $HOME/.dir_colors/dircolors`

if [[ `hostname` == *"xps"* ]]; then
	xmodmap -e "keycode 94 = Shift_L NoSymbol Shift_L"
fi

xset r rate 200 30

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PATH=/home/joseph/.sit-install:$PATH

export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

# tabtab source for packages
# uninstall by removing these lines
[[ -f /.config/tabtab/__tabtab.zsh ]] && . ~/.config/tabtab/__tabtab.zsh || true
