#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

setxkbmap -option ctrl:swapcaps

xset mouse 2/3 0

# Customize to your needs...

export TERM="xterm-256color"
stty -ixon

# aliases
alias setclip='xclip -selection c'
alias getclip='xclip -selection clipboard -o'


[[ -s '~/.secretrc' ]] && source '~/.secretrc'


[[ -s "~/.gvm/scripts/gvm" ]] && source "~/.gvm/scripts/gvm"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

[[ -s "/home/jbuchma/.gvm/scripts/gvm" ]] && source "/home/jbuchma/.gvm/scripts/gvm"
